INSERT INTO tb_user (name, email, password) VALUES ('Bob Evans', 'bob@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Ana Paula', 'ana@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');

INSERT INTO tb_role (authority) VALUES ('ROLE_VISITOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_MEMBER');

INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);

INSERT INTO tb_genre (name) VALUES ('Terror');
INSERT INTO tb_genre (name) VALUES ('Ação');
INSERT INTO tb_genre (name) VALUES ('Comédia');
INSERT INTO tb_genre (name) VALUES ('Desenho');

INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('A Freira', 'Implore perdão', 2018, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/fgsHxz21B27hOOqQBiw9L6yWcM7.jpg', 'Presa em um convento na Romênia, uma freira comete suicídio. Para investigar o caso, o Vaticano envia um padre assombrado e uma noviça prestes a se tornar freira. Arriscando suas vidas, a fé e até suas almas, os dois descobrem um segredo profano e se confrontam com uma força do mal que toma a forma de uma freira demoníaca e transforma o convento em um campo de batalha.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Olhos Famintos', 'O que você come?', 2001, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/m0yTFeh8vrsMP0fQDdYGSh4xthX.jpg', 'Ao voltarem para casa por uma estrada sem movimento, os irmãos Trish e Darry veem um vulto atirando o que parece ser um corpo embrulhado. Parando para investigar, eles descobrem centenas de corpos mutilados, pendurados embaixo de uma antiga igreja.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('It - A Coisa', 'Você também vai flutuar.', 2017, 'https://www.themoviedb.org/t/p/w220_and_h330_face/uYxz0lIiNgErrPhQbSjUdwYxtFc.jpg', 'Um grupo de sete adolescentes de Derry, uma cidade no Maine, formam o auto-intitulado "Losers Club", o clube dos perdedores. A pacata rotina da cidade é abalada quando crianças começam a desaparecer e tudo o que pode ser encontrado delas são partes de seus corpos. Logo, os integrantes do "Losers Club" acabam ficando face a face com o responsável pelos crimes: o palhaço Pennywise.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Ava', 'Kill. Or be killed.', 2020, 'https://www.themoviedb.org/t/p/w220_and_h330_face/6llUjNLsLiAcpIOer9LR631HPoU.jpg', 'Atormentada por dúvidas, uma assassina de elite luta para proteger a si mesma e a sua família depois que uma missão dá errado.', 2);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Power', 'O que você arriscaria por cinco minutos de puro poder?', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/qVygtf2vU15L2yKS4Ke44U4oMdD.jpg', 'Um ex-soldado, uma adolescente e um policial varrem New Orleans em busca de uma pílula perigosa que desperta superpoderes temporários.', 2);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Esquadrão 6', 'Dizem que ninguém pode salvar o mundo. Conheça Ninguém.', 2019, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/eFw5YSorHidsajLTayo1noueIxI.jpg', 'Após forjar a própria morte, um bilionário monta uma equipe de profissionais internacionais para a ousada e sanguinária missão de derrubar um ditador cruel.', 2);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Resgate', 'When the mission ends, redemption begins', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/1R6cvRtZgsYCkh8UFuWFN33xBP4.jpg', 'Em Bangladesh, o mercenário Tyler Rake luta para sobreviver durante a missão para resgatar o filho de um chefão do crime.', 2);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('As Branquelas', 'Eles estão disfarçados.', 2004, 'https://www.themoviedb.org/t/p/w220_and_h330_face/tW3ovNQsn5jPDB5E9B4KeCNA6kU.jpg', 'Os irmãos Marcus (Marlon Wayans) e Kevin Copeland (Shawn Wayans) são detetives do FBI que estão com problemas no trabalho. A última investigação da dupla foi um grande fracasso e eles estão sob a ameaça de serem demitidos. Quando um plano para sequestrar as mimadas irmãs Brittany (Maitland Ward) e Tiffany Wilson (Anne Dudek) é descoberto, o caso é entregue aos principais rivais dos irmãos Copeland, os agentes Vincent Gomez (Eddie Velez) e Jack Harper (Lochlyn Munro). Para aumentar ainda mais a humilhação da dupla, eles são escalados para escoltar as jovens mimadas do aeroporto até o local de um evento pelo qual elas esperaram por meses. Porém no trajeto um acidente de carro provoca um verdadeiro desastre: enquanto uma das irmãs arranha o nariz, a outra corta o lábio. Desesperadas, elas se recusam a ir ao evento. É quando,para salvar o emprego, Marcus e Kevin decidem por assumir as identidades das irmãs.', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Vovó... Zona', 'This FBI agent is going undercover... and he''s concealing more than a weapon.', 2000, 'https://www.themoviedb.org/t/p/w220_and_h330_face/it9QRBO1jmbAC2HC6Zd3Uk0mlMn.jpg', 'O agente do FBI Malcolm Turner (Martin Lawrence) é duro, inteligente e um mestre dos disfarces. Não há nada em que ele não possa se disfarçar. A mais recente missão de Malcolm é numa pequena cidade sulista, onde ele deve capturar um perigoso assaltante de banco que fugiu recentemente da prisão. Para tanto, Malcolm arma uma tocaia em frente à casa de uma matriarca conhecida como Vovózona, que está para receber a visita da última namorada do ladrão, Sherry, e seu filho. Só que surge um problema: inesperadamente Vovózona deixa a cidade. Para levar adiante seu plano, Malcolm resolve ele mesmo se disfarçar de Vovó para poder capturar o assaltante.', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Mr. Bean', 'Disaster is just a small step away', 1990, 'https://www.themoviedb.org/t/p/w220_and_h330_face/CLuO9WBCI0fYmV9hkz2qA9Tg0W.jpg', 'A personalidade de Mr. Bean é agradável, divertida, inclusive ingênua, e, algumas vezes, malvada. Ele vive em seu pequeno apartamento no norte de Londres com seu ursinho, Teddy.', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('A Proposta', 'Você aceitaria?', 2009, 'https://www.themoviedb.org/t/p/w220_and_h330_face/7BkfGYq0IQF9NnNmNbdxeshhn1t.jpg', 'Margaret Tate (Sandra Bullock) é uma poderosa editora de livros, que se vê em apuros ao ser comunicada de sua deportação para o país-natal, o Canadá. Para evitar que isto ocorra ela declara estar noiva de Andrew Paxton (Ryan Reynolds), seu assistente. Perseguido por Margaret há anos, ele aceita participar da farsa mas impõe algumas condições', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('A Verdade Nua e Crua', 'The battle of the sexes is on.', 2009, 'https://www.themoviedb.org/t/p/w220_and_h330_face/1omIRNiqO4c0CkKWlI1Yz8TFE0E.jpg', 'Abby Richter é uma competente e conservadora produtora de um programa de televisão. Com a audiência caindo, seu chefe tem a ideia de contratar o concorrente Mike Chadway. Assim, a controladora e eterna romântica Abby se vê obrigada a aceitar como colaborador um cara machista, grosseiro e especialista em revelar o que realmente atrai os homens. Com as relações amorosas em baixa, ela recorre aos serviços do consultor para conquistar o vizinho e o resultado obtido acaba sendo além do esperado.', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('O Rei Leão', 'A maior aventura da vida, é descobrir o seu lugar no ciclo da vida.', 1994, 'https://www.themoviedb.org/t/p/w220_and_h330_face/8aIvm8OaJISOpVTt7rMIh7X35G5.jpg', 'Mufasa, o Rei Leão, e a rainha Sarabi apresentam ao reino o herdeiro do trono, Simba. O recém-nascido recebe a bênção do sábio babuíno Rafiki, mas ao crescer é envolvido nas artimanhas de seu tio Scar, o invejoso e maquiavélico irmão de Mufasa, que planeja livrar-se do sobrinho e herdar o trono.', 4);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Procurando Nemo', 'Existem 3.7 trilhões de peixes no oceano, eles estão procurando por um.', 2003, 'https://www.themoviedb.org/t/p/w220_and_h330_face/qx0EDGXslJvH4qU3DCTseNUL2wo.jpg', 'Depois que seu filho é capturado na Grande Barreira de Corais e levado para Sydney, um peixe-palhaço tímido parte em uma jornada para trazê-lo para casa.', 4);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Monstros S.A.', 'No susto e no grito, fazemos bonito.', 2001, 'https://www.themoviedb.org/t/p/w220_and_h330_face/5p6cdAeUevsLOX0oI1T4JIul4QO.jpg', 'Sulley e seu falante assistente Mike trabalham na Monstros S.A., a maior fábrica de processamento de gritos de Monstrópolis. A principal fonte de energia do mundo dos monstros provém da coleta dos gritos das crianças humanas. Só que os montros acreditam que as crianças são tóxicas e, quando uma menininha invade o mundo deles, começa a maior confusão.', 4);

INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Muito engraçado! Os atores são muito bons!', 8, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Filme divertido, tem bastante cenas engraçadas e um final surpreendente!', 11, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Excelente filme para crianças! Nos faz refletir sobre muitas coisas', 13, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Não gostei do filme! Dá muito medo!', 1, 2);